#!/bin/bash
write=$(dd if=/dev/zero bs=1024k of=tstfile count=1024 2>&1 | awk '/sec/ {print $1 / $5 / 1048576, "MB/sec" }')
echo "Write speed is $write"
purge

read=$(dd if=tstfile bs=1024k of=/dev/zero count=1024 2>&1 | awk '/sec/ {print $1 / $5 / 1048576, "MB/sec" }')
echo "Read speed is $read"
purge
rm tstfile
